### ISSUE TITLE
Support for Finalizer Functions

### ISSUE THREAD

**Issue by Shinmera** [clasp-developers/clasp#254] opened 2016-05-25 14:31 UTC
Currently finalizer functions are not supported within clasp. This is a roadblock that prevents Clasp from being used with major libraries and applications. Finalizers provide a way to run a function at the point in time just before the object the function is tied to is being garbage collected. In order for this to work correctly, support for it in both the Boehm and MPS configurations of Clasp must be added.

In the trivial-garbage library the finalizers are provided through the `finalize` function, which needs to add explicit support for Clasp once it is ready.

**Comment by drmeister** [comment] 2016-12-04 06:20
I'm adding support for this now.  It's a good time because I've been messing around with allocators and GC.

I've got finalizers working with Boehm - and now I'm testing them in MPS.

**Comment by Shinmera** [comment] 2016-12-04 10:17
Great! This means that soon I can run some good tests of Clasp's CFFI capabilities with some of my systems.

**Comment by drmeister** [comment] 2016-12-06 13:14
I added finalizers in 7bb01cffac57a3c898a8ce0e5af81847067d09fd but screwed up the issue number (245 rather than 254) in the commit message.

**Comment by drmeister** [comment] 2016-12-06 13:16
I added support for finalizers for Boehm and MPS.
(gctools:finalize object func)   and (gctools:definalize object).
They work exactly like trivial garbage expects them to work.

I also added a regression test in clasp/src/lisp/tests/regressions/finalizers.lisp   - but they didn't get committed - fixing now.

**Comment by drmeister** [comment] 2016-12-06 13:17
Finalizer regression tests pushed.

**Comment by kpoeck** [comment] 2019-05-08 22:05
TEsts are working, interface is available

**Closed** 2019-05-08 22:05 UTC
Labels: enhancement
