### ISSUE TITLE
Wrong code generation with newest eclector in clasp

### ISSUE THREAD

**Issue by kpoeck** [clasp-developers/clasp#866] opened 2019-10-14 21:59 UTC
Using current eclector in clasp gives an error compiling any code that has a #<something>, e.g. #+ 

To reproduce use the following simplified code
```lisp
;;;Beginning File clasp-eclector-error

(in-package :cl-user)

(defun parse-parameter-and-sub-char (stream)
  (values stream #\+))

(defun eclector.readtable.get-dispatch-macro-character (readtable disp-char sub-char)
  (unless (characterp sub-char)
    (error "Character lost"))
  (list readtable disp-char sub-char))

(defun make-dispatch-invoker (readtable disp-char)
  (alexandria:named-lambda dispatcher (stream char)
    (declare (ignore char))
    (multiple-value-bind (parameter sub-char)
        (handler-case
            (parse-parameter-and-sub-char stream)
          (end-of-file (condition)
            (error "should not happen ~a" condition)
            (return-from dispatcher)))
      (let ((macro-function
             (eclector.readtable.get-dispatch-macro-character
              readtable disp-char sub-char)))
        (values macro-function parameter)))))

(defparameter *lambda* nil)

(defun init ()
  (setq *lambda* (make-dispatch-invoker *readtable* #\#)))

(defun use-it ()
  (funcall *lambda* :stream #\#))

;;;End clasp-eclector-error
````
e.g. Compile/Load File in slime
```lisp
(init)
(use-it)
--> error "Character lost", sub-char is garbage
Trying to print sub-char -> segmentation-error
````

In older eclectors, make-dispatch-invoker just use a lambda, not a named lambda, that seem to compile fine

**Comment by kpoeck** [comment] 2019-10-15 19:38
Or simpler
```lisp
;;;Beginning File clasp-eclector-error

(in-package :cl-user)

(defun parse-parameter-and-sub-char (stream)
  (values stream #\+))

(defun eclector.readtable.get-dispatch-macro-character (readtable disp-char sub-char)
  (unless (characterp sub-char)
    (error "Character lost"))
  (list readtable disp-char sub-char))

(defun make-dispatch-invoker (readtable disp-char)
  (labels ((dispatcher (stream char)
             (declare (ignore char))
             (multiple-value-bind (parameter sub-char)
                 (handler-case
                     (parse-parameter-and-sub-char stream)
                   (end-of-file (condition)
                     (error "should not happen ~a" condition)
                     (return-from dispatcher)))
               (let ((macro-function
                      (eclector.readtable.get-dispatch-macro-character
                       readtable disp-char sub-char)))
                 (values macro-function parameter)))))
    #'dispatcher))

(defun fail ()
  (funcall (make-dispatch-invoker *readtable* #\#) :stream #\#))

;;;End clasp-eclector-error
````
Calling (fail) -> (error "Character lost"))

**Comment by kpoeck** [comment] 2019-10-16 19:07
perhaps similar to #739 ?

**Comment by kpoeck** [comment] 2019-10-16 19:35
Works fine, if I drop the (return-from dispatcher)

**Comment by drmeister** [comment] 2019-12-22 02:35
This looks like a cleavir problem rather than an eclector problem.
If you comment out the (return-from dispatcher) using #+(or) the code works fine. 
Something about the (return-from dispatcher) after the (error "should not happen ~a" condition) is messing up the multiple-value return.

```
;; This buffer is for text that is not saved, and for Lisp evaluation.
;; To create a file, visit it with C-x C-f and enter text in its buffer.

;;;Beginning File clasp-eclector-error

(in-package :cl-user)

(defun fail ()
  (labels ((dispatcher ()
             (multiple-value-bind (bbb ddd)
                 (BLOCK mmm
                   (LET ((CORE::*HANDLER-CLUSTERS* nil))
                     (RETURN-FROM mmm (values #\# #\+)))
                   (RETURN-FROM mmm
                     (RETURN-FROM DISPATCHER)))
               (unless (characterp ddd) (error "The character lost")))))
    (dispatcher)))

(defun fail2 ()
  (block fail22
    (multiple-value-bind (bbb ddd)
        (BLOCK mmm
          (LET ((CORE::*HANDLER-CLUSTERS* nil))
            (RETURN-FROM mmm (values #\# #\+)))
          (RETURN-FROM mmm
            (RETURN-FROM fail22)))
      (unless (characterp ddd) (error "The character lost")))))


(defun doesnt-fail3 ()
  (block fail33
    (MULTIPLE-VALUE-CALL
        #'(LAMBDA (&OPTIONAL (BBB) (DDD) &REST eee)
            (DECLARE (IGNORE eee))
            (UNLESS (CHARACTERP DDD) (ERROR "The character lost")))
      (BLOCK MMM
        (LET ((CORE::*HANDLER-CLUSTERS* NIL))
          (RETURN-FROM MMM (VALUES #\# #\+)))
        (RETURN-FROM MMM (RETURN-FROM FAIL33))))))

;;; fail, fail2 fail
;;; doesnt-fail3 doesn't fail although its a macroexpansion of fail2

```

**Comment by Bike** [comment] 2020-01-02 14:59
I'm pretty certain this is a Cleavir problem. I'm not sure of the details but I think this is how it goes.

First off, the reason drmeister didn't observe a fail with the `multiple-value-call` is that that macroexpansion isn't actually used. There's a cleavir-dependent compiler macroexpansion that's used instead. That will look like the following:

```
(defun fail4 ()
  (block fail22
    (CLEAVIR-PRIMOP:LET-UNINITIALIZED (BBB4986 DDD4987)
     (CLEAVIR-PRIMOP:MULTIPLE-VALUE-SETQ (BBB4986 DDD4987)
      (BLOCK MMM
        (LET ((CORE::*HANDLER-CLUSTERS* NIL))
          (RETURN-FROM MMM (VALUES #\# #\+)))
        (RETURN-FROM MMM (RETURN-FROM FAIL22))))
     (LET ((BBB BBB4986) (DDD DDD4987))
       (UNLESS (CHARACTERP DDD) (ERROR "The character lost")))))
```

Secondly, the special variable binding is necessary for the problem because our use of `call-with-variable-bound` ensures there is a distinct inner function, like `(lambda () (return-from mmm (values #\# #\+)))`. You can replace the let form with `(apply (lambda () (return-from mmm (values #\# #\+))))` (with just `funcall` the problem won't occur, since the function will be inlined).

Now the actual problem I think is this. `let-uninitialized` doesn't actually set the variable - that's the whole point - it just tells the compiler it exists. Without the second `return-from`, Cleavir generates (never executed) code to set the `BBB4986` variable both inside the inner function, and after that function returns (because it doesn't know it never returns). As such, there is one set to `BBB4986` in `fail4` and one in the inner function, so Cleavir recognizes it as a closure variable and generates code to deal with it like that - and that works. With the `return-from`, however, nothing in `fail4` sets `BBB4986` and `DDD4987`, and so only the inner function sets the variable. While it's still read in `fail4`, Cleavir doesn't seem to deal with the situation properly - either it doesn't recognize it's a closure variable, or doesn't know how to deal with the cells right. I think the former. So HIR is generated in which the inner function sets the variables, and `fail4` then reads a distinct, never-initialized `DDD4987` with the same name.

**Comment by kpoeck** [comment] 2020-02-03 19:08
I think I hit that same problem crosscompiling scbl:
```lisp
(defun foo (string)
  (list string))

(defun extract-user-fun-directives (string)
  (let* ((tokens (handler-case
                     (foo string)
                   (error (e)
                     (declare (ignore e))
                     (return-from extract-user-fun-directives (values nil nil)))))
         (max-len (loop for token in tokens
                     sum (if (string token)
                             23
                             (length token)))))
    max-len))
(extract-user-fun-directives "123")
--> all kind of wrong error messages, since tokens is garbage, e.g. 
COMMON-LISP-USER> (extract-user-fun-directives "123")
Condition of type: TYPE-ERROR
1262556672 is not of type (AND (AND (OR CONS (MEMBER NIL)))).
````

**Comment by Bike** [comment] 2020-03-18 14:55
Can't reproduce with the `extract-user-fun-directives` one: it consistly returns 23. Still works with my earlier example modified to not rely on dynamic binding, i.e.

```lisp
(defun fail4 ()
  (block fail22
    (CLEAVIR-PRIMOP:LET-UNINITIALIZED (BBB4986 DDD4987)
     (CLEAVIR-PRIMOP:MULTIPLE-VALUE-SETQ (BBB4986 DDD4987)
      (BLOCK MMM
        (apply (lambda () (return-from mmm (values #\# #\+))) nil)
        (RETURN-FROM MMM (RETURN-FROM FAIL22))))
     (LET ((BBB BBB4986) (DDD DDD4987))
       (UNLESS (CHARACTERP DDD) (ERROR "The character lost"))))))
```

gonna see about fixing

**Comment by Bike** [comment] 2020-03-19 12:34
This commit changes `multiple-value-bind` so that the original example works for me now. The later examples that use `let-uninitialized` explicitly are still broken because Cleavir is still broken. We may want to file a bug there, but I don't know if it happens in Cleavir2 as well.

**Comment by kpoeck** [comment] 2020-03-19 19:12
I can confirm that my example works

**Comment by Bike** [comment] 2020-03-20 22:32
You mean your original example, or the one you got from cross compiling SBCL?

**Comment by kpoeck** [comment] 2020-03-21 06:10
my original but also can't reproduce the sbcl cross problem

**Closed** 2020-03-23 18:37 UTC
Labels: bug
