### ISSUE TITLE
 (let ((x (gensym))) (write (list x x) :circle t))   doesn't generate the right result

### ISSUE THREAD

**Issue by drmeister** [clasp-developers/clasp#350] opened 2017-04-29 21:04 UTC
Which would be...

(#1=#:G449 #1#)
(#:G449 #:G449)

**Comment by drmeister** [comment] 2017-04-29 21:06
(let ((*print-circle* t)) (let ((x (gensym))) (print (list x x)) nil))   --> (#:G1028 #:G1028)   FAIL

**Comment by Bike** [comment] 2017-06-04 02:32
Think this is a dupe of #68 part two

**Closed** 2018-07-25 17:57 UTC
Labels: bug
